version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: always
        
  member-service:
    build: ./members
    volumes:
      - ./members:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - db
    restart: always

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - member-service
    restart: always
